### ISSUE TITLE
 No such file or directory: '/home/jhendrick/ForkHub/app/build/outputs/apk/app-release-unsigned.apk'

### ISSUE THREAD

**Issue by justinjhendrick** [timmutton/redex-plugin#10]
Introduced by either ada751fd6e2180d367a0feb97e7f1fec79293bd0 or 430730da074abc3e48e956598cb59db3581feb00

```
Before redex:
        0 methods
        0 fields
        0 bytes
Traceback (most recent call last):
  File "/tmp/redex.FQU7SA/redex.py", line 636, in <module>
    run_redex(args)
  File "/tmp/redex.FQU7SA/redex.py", line 498, in run_redex
    unzip_apk(args.input_apk, extracted_apk_dir)
  File "/tmp/redex.FQU7SA/redex.py", line 210, in unzip_apk
    with zipfile.ZipFile(apk) as z:
  File "/usr/lib/python3.5/zipfile.py", line 1009, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jhendrick/ForkHub/app/build/outputs/apk/app-release-unsigned.apk'
After redex:
        0 methods (%NaN of original)
        0 fields (%NaN of original)
        0 bytes (%NaN of original)
```

**Comment by timmutton** [comment]
My bad, wasnt updating the input file name after moving it
